export const propertyConstants = {
    GET_PROPERTY_REQUEST:"GET_PROPERTY_REQUEST",
    GET_PROPERTY_SUCCESS:"GET_PROPERTY_SUCCESS",
    GET_PROPERTY_FAILURE:"GET_PROPERTY_FAILURE"
}
export const singlePropertyConstants = {
    SINGLE_PROPERTY_REQUEST:"SINGLE_PROPERTY_REQUEST",
    SINGLE_PROPERTY_SUCCESS:"SINGLE_PROPERTY_SUCCESS",
    SINGLE_PROPERTY_FAILURE:"SINGLE_PROPERTY_FAILURE"
}